export const menuLinks = [
    { name: "Home", link: "./dashboard", icon :"home" },
    { name: "Order", link: "./location", icon : "trash-bin"},
    { name: "Wallet", link: "./wallet", icon : "wallet"},
    { name: "Profile", link: "./profile", icon : "person"},
    { name: "About", link: "#", icon : "information-circle"},
    { name: "Logout", link: "./home", icon : "log-out"},
  ];
export const navLinks = [
    { name: "Home", link: "/"},
    { name: "Menu", link: "/menus"},
    { name: "About", link: "/about"},
    { name: "Contact", link: "/#contact"},
    { name: "Login", link: "/login"},
  ];

export const menuBtns = [
    { name: "Popular", id :"popular"},
    { name: "Diabetics", id: "diabetics"},
    { name: "Vegetarian", id: "vegan" },
  ];


export const ourMenu = [{
    id: 1,
    tittle: "Rice",
    category: "popular",
    img: "https://th.bing.com/th/id/R.971bafeb6ac3de422742cd5358f48896?rik=8kIZBoq%2bh%2bMsQQ&riu=http%3a%2f%2fanswersafrica.com%2fwp-content%2fuploads%2f2016%2f03%2fnigerian-rice-and-stew.jpg&ehk=%2fJtAVLxbTvVuMh%2fD4GMW%2fULqIjV%2fq5qk%2fgagXiwCJbs%3d&risl=&pid=ImgRaw&r=0",
    desc: "The locally grown in Nigeria rice and stew, it contains a lot of vitamins, minerals and fiber which makes it good for diabetic patients. A very good substitute for white rice par-boiled with stem",
    price: 1700,
    rating: 4.5,
},
{
    id: 3,
    tittle: "Pounded Yam",
    category: "dinner",
    img: require("./assets/foods/poundedYam.jpg"),
    desc: "Pounded yam is one of the most popular foods in Nigeria. pounded yam made form yam cooked and pounded to swallow and egusi soup made from Egusi seeds or pumpkin seeds are a good source of protein, minerals and unsaturated fats including omeda-3.",
    price: 2500,
    rating: 5,
},
{
    id: 37,
    tittle: "Abacha",
    category: "vegan",
    img: "https://healthguide.ng/wp-content/uploads/2022/11/images-2022-11-07T085759.048.jpeg?ezimgfmt=ng:webp/ngcb1",
    desc: "Abacha is popular food in the South eastern parts of Nigeria. It is prepared with dried shredded cassava, utazi leaves, pepper, potash, red oil, ugba (ukpaka), and diced garden eggs, It is very nutritious and has a lot of nutritional benefits.",
    price: 1650,
    rating: 4,
},
{
    id: 39,
    tittle: "Yam Pottage",
    category: "vegan",
    img: "https://th.bing.com/th/id/R.b9da652f63190f19b37df956adbda814?rik=lGBCrKpkJ1mHtQ&pid=ImgRaw&r=0",
    desc: "Another nice dish made with yam. Yam pottage is a satisfying, one-pot option that you can never go wrong with. Cook it with your favourite spices, and you can even add plantain to it. Yam porridge is also a great vegan food in Nigeria.",
    price: 1650,
    rating: 4,
},
{
    id: 40,
    tittle: "Jollof Rice and Salad",
    category: "vegan",
    img: "https://th.bing.com/th/id/R.62db7c9ff6df932dfdedada1b17fa9b2?rik=WT4dESWRtHQrFA&pid=ImgRaw&r=0",
    desc: "This is another great  option. Rather than top your plate of jollof rice with a serving of turkey or chicken, you can just have it with salad instead. Jollof rice and salad is a very interesting combo that would leave you quite satisfied. <br>To make your salad, you need vegetables like cabbage, lettuce, carrots, cucumber, and so on. All of these vegetables are bursting with nutrients that your body needs.",
    price: 1650,
    rating: 4,
},
{
    id: 5,
    tittle: "Pap",
    category: "vegan",
    img: require("./assets/foods/pap.jfif"),
    desc: "This is another very common Nigerian breakfast dish. In most homes, both the Akara and pap are bought from street vendors who fry the akara on the spot, so you buy it steaming hot. Some people for different reasons, process and fry theirs at home. Akara is a beans fritter made from beans paste while the pap is a paste made from grains, mostly corn but also millet etc. It is turned into a gruel to go with the akara using boiling water.",
    price: 1000,
    rating: 4.5,
},
{
    id: 11,
    tittle: "Whaet",
    category: "diabetics",
    img: "https://th.bing.com/th/id/OIP.nuGYvGoPpXgrBSbd9oNzxQHaE8?w=252&h=180&c=7&r=0&o=5&pid=1.7",
    desc: "Wheatmeal fufu (Swallow wheat) is a dish prepared as a form of “Swallow” in Nigeria. It can be taken with any Nigerian soup in form of morsels. It is rich in superior fiber which helps in curbing the rate at which sugar is absorbed from the intestinal tract and it aids in weight loss by making you feel fuller.",
    price: 1900,
    rating: 5,
},
{
    id: 2,
    tittle: "okro",
    category: "diabetics",
    img: "https://th.bing.com/th/id/OIP.SkaCk0VR8XNoCGEubdNfjwHaE8?pid=ImgDet&w=720&h=480&rs=1",
    desc: "Okro is a common and popular vegetable used widely in preparing soups in Nigeria. It is also used in other parts of the world to prepare delicacies. Okra is rich in antioxidants, minerals and other nutrients. It has loads of health benefits aside from helping people with diabetes",
    price: 500,
    rating: 4.5,
},
{
    id: 7,
    tittle: "mOI-mOI",
    category: "diabetics",
    img: "https://th.bing.com/th/id/R.fb40ab4d6dc1681093466273b7142d41?rik=er6X1xbE2%2bIZnQ&pid=ImgRaw&r=0",
    desc: "Nigerian Bean Cake popularly known as Moi moi is a good meal that should feature often in the diet plan for diabetics. Beans is rich in protein and minerals and with a low glycemic index , it will not cause spikes in blood sugar levels. It can be eaten with a vegetable sauce",
    price: 700,
    rating: 5,
},
{
    id: 8,
    tittle: "Suya",
    category: "dinner",
    img: "https://th.bing.com/th/id/OIP.j0yZNJptcx2qH8Nrl82FDAEsDh?pid=ImgDet&rs=1",
    desc: "Thin Strips Of Seasoned, Grilled Beef, Thin slices of beef are marinated in an array of spices- a combination that’ll ignite your mouth. Typical spices used include roaster peanut powder, cayenne, and ginger.",
    price: 1800,
    rating: 5,
},
{
    id: 9,
    tittle: "Eba",
    category: "dinner",
    img: require("./assets/foods/eba.jfif"),
    desc: "Eba or garri is a Nigerian staple food consisting of cassava flour combined with hot water. The combination is traditionally mixed with a large wooden spoon until it firms up, and is then rolled into a ball. Eba is served with almost all Nigerian soups. It can be dipped into the soups, but it's also often served with stews and various meat dishes.",
    price: 1400,
    rating: 5,
},
{
    id: 10,
    tittle: "Amala",
    category: "dinner",
    img: require("./assets/foods/amala.jfif"),
    desc: "Amala and Ewedu soup is a popular food among the Yorubas in Nigeria, With complement of Ewedu Soup/Jute leaves has a lot of health benefits aside from regulating blood sugar levels and stabilizing blood pressure.",
    price: 2250,
    rating: 5,
},
{
    id: 12,
    tittle: "Yam and source",
    category: "vegan",
    img: "https://www.bing.com/images/search?q=Fried+Yams+Nigeria&FORM=IRTRRL",
    desc: "Yam is a good source of carbohydrates, which provides the body with energy. Tomatoes are loaded with vitamins and other nutrients that would help protect your body from diseases. ",
    price: 700,
    rating: 4.5,
},
{
    id: 13,
    tittle: "Tuwo shinkafa",
    category: "dinner",
    img: require("./assets/foods/semo.jfif"),
    desc: "Tuwo shinkafa is a unique Nigerian dish consisting of rice flour or soft, short-grained rice and water. The combination of those ingredients is cooked, mashed, and formed into large balls. It is popular throughout the northern parts of the country, and is often served as an accompaniment to various soups and stews.",
    price: 1800,
    rating: 5,
},
{
    id: 14,
    tittle: "plantain",
    category: "diabetics",
    img: "https://th.bing.com/th/id/R.5b004d4a150185275ec534da300bf4ed?rik=BDC3uXYywoiHWg&riu=http%3a%2f%2fi.siteapi.org%2ffAj2D_Rbw45gsVvcSq3anKwz8Ak%3d%2ffit-in%2f1024x768%2fcenter%2ftop%2ffilters%3aquality(95)%2fb843cbeba53ed1c.s.siteapi.org%2fimg%2fbd2e1dc3cfb0d44feb277d6158f8d95e824a62f3.jpg&ehk=3GhhauhJkgUNGdHt%2bYkkWHBb5gtsahICT9qRuEQ%2bg%2bs%3d&risl=&pid=ImgRaw&r=0",
    desc: "One of the best diets for diabetics. Unripe plantains are rich in vitamins, mineral, antioxidants and fiber. It has low sugar and has high resistant starch content which makes it a good choice for diabetic",
    price: 1400,
    rating: 4.5,
},
{
    id: 15,
    tittle: "Ogbono Soup",
    category: "diabetics",
    img: "https://cdn-bmalj.nitrocdn.com/uirOOtSrYrqqUksKHkiSCjZGZlPeXsmk/assets/static/optimized/rev-939cb5a/images/Nigerian-Food-Pounded-Yams.jpg",
    desc: " Ogbono soup is a slippery draw soup made with blended Ogbono seeds. Ogbono translates to mango!, whene you eat it, you’ll be getting tons of nutrients such as proteins, fibers, healthy fats, and calcium. It’s another vegetable soup you can eat several times and never have the same experience twice.",
    price: 1000,
    rating: 5,
},
{
    id: 16,
    tittle: "Pepper Soup",
    category: "dinner",
    img: "https://th.bing.com/th/id/R.87b9f598e635d21441f5f4bb041a0252?rik=6MHX6GHfPXPOiA&pid=ImgRaw&r=0",
    desc: "This type of soup is often made with goat meat. Spices such as ginger and red chili flakes are used for a punch of flavor. African cuisine is packed with tons of soups and stews, but pepper soup is one recipe you’ll want for the rest of your life after trying it.",
    price: 2000,
    rating: 5,
},
{
    id: 38,
    tittle: "Okpa",
    category: "vegan",
    img: "https://www.thepretendchef.com/ezoimgfmt/i0.wp.com/www.thepretendchef.com/wp-content/uploads/2016/07/okpa-1-9-1.jpg?w=609&ssl=1&ezimgfmt=ng:webp/ngcb1",
    desc: "Okpa is the local name for Bambara nuts. It is also the name of the boiled pudding made with the Bambara nut powder. Although okpa is very easy to make, hardly anybody makes their own okpa, rather most people feel it’s not worth the trouble to make it at home so they buy from the numerous okpa vendors. It is mostly sold in the eastern part of Nigeria. Okpa is very filling and can keep hunger away until lunch. It is excellent for diabetics.",
    price: 1650,
    rating: 5,
},
{
    id: 17,
    tittle: "Better leaf soup",
    category: "deibetics",
    img: require("./assets/foods/betterleaf.png"),
    desc: "Bitter leaf is a popular leaf used widely in Nigeria in preparing local delicacies like soups and dishes. Bitterleaf soup is a special delicacy of Igbo tribe of Nigeria. It is also used for medicinal purposes. Studies show that bitter leaf has anti-cancerous properties, regulates blood pressure and also helpful in the management of diabetes",
    price: 1800,
    rating: 5,
},
{
    id: 18,
    tittle: "Afang soup",
    category: "diabetics",
    img: "https://cdn.tasteatlas.com//images/dishes/662c50d9d8ec4760bb12d705f64897d6.jpg?w=905&h=510",
    desc: "This soup is peculiar to the Efik and Ibibio tribes of Nigeria. It is rich in vegetables which helps in controlling blood sugar and also reduces weight gain, therefore good for diabetics. Afang is made from Okazi leaves and waterleaves.",
    price: 2200,
    rating: 5,
},
{
    id: 19,
    tittle: "Tomato Stew",
    category: "general",
    img: "https://th.bing.com/th/id/R.64393ce39109cbd4fe016ba0ffd3e2be?rik=O4dveHGOheZ7%2fw&pid=ImgRaw&r=0",
    desc: "This simple dish brings back nostalgic home memories for many Nigerian households. It’s made with roasted peppers, chicken drumsticks, and African spices, The roasted peppers deliver an out-of-this-world flavor and are paired best with rice or pounded yams. When eating any type of Nigerian stew, make sure your pants are stretchy. “Hearty” is an understatement.",
    price: 1800,
    rating: 4.5,
},
{
    id: 22,
    tittle: "Zobo",
    category: "vegan",
    img: "https://th.bing.com/th/id/R.b5b2dec40e198d9c168dc6848200432d?rik=%2fCUazFBivw4XUg&pid=ImgRaw&r=0",
    desc: "Zobo is a nutritious drink made from dried hibiscus flowers. These dried flowers are usually boiled in water with great aromatic spices like ginger, vanilla and any aromatic spice you want to add. It is best served cold. Zobo is usually taken with other snacks. It’s definitely among the most popular foods in Nigeria.",
    price: 1400,
    rating: 4.5,
},
{
    id: 32,
    tittle: "Beans",
    category: "diabetics",
    img: "https://healthguide.ng/wp-content/uploads/2021/10/Screenshot_2021-10-31-17-48-41-43.jpg?ezimgfmt=ng:webp/ngcb1",
    desc: "Beans are low in fat and calories but has a high protein content. They are also rich in fiber and rank low in he glycemic index which makes it a good meal for people with diabetes",
    price: 1050,
    rating: 5,
},
{
    id: 35,
    tittle: "Jollof Rice",
    category: "general",
    img: "https://cdn.tasteatlas.com//images/dishes/41ca6dfc48714647a813a6c1333a9e94.jpg?w=905&h=510",
    desc: "Jollof rice is Nigeria's national dish. In order to prepare it, rice is cooked in a rich tomato sauce so that it soaks in all the flavors. The most common ingredients found in jollof rice include rice, tomatoes, tomato paste, onions, salt, and pepper. On top of that, any kind of meat, vegetable, fish or spice can be added. It is important to have a delicious sauce, so in addition to tomatoes, there are also ingredients such as coconut milk, nutmeg, partminger (African basil leaf) and sometimes even Roiboos tea used in the sauce. ",
    price: 1650,
    rating: 5,
},

];

//  //footer
// Products
export const products = [
    { name: "Home", link: "/"},
    { name: "Menu", link: "/menus"},
    { name: "blog", link: "/blog"},
  ];

export const usefulLinks = [
    { name: "Pricing", link: "/"},
    { name: "Setting", link: "/menus"},
    { name: "Help", link: "/about"},
  ];